namespace GameStore.Api.Endpoints;

using GameStore.Api.Data;
using GameStore.Api.Dtos;
using GameStore.Api.Models;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.EntityFrameworkCore;

public static class GamesEndpoints
{
    const string GetGameEndpoint = "GetGameById";

    // We add an extension method to the WebApplication class to define our endpoints in a separate class and keep our Program.cs file clean and organized
    // Extending means that we add new methods to an existing class without modifying the original class or creating a new derived class. We can call the extension method as if it were a regular method of the extended class, which makes our code more readable and maintainable
    public static void MapGamesEndpoints(this WebApplication app)
    {
        // We create a group of endpoints with the prefix /games and we add a tag to the group for documentation purposes (we will see this in the next section when we add Swagger to our API)
        var group = app.MapGroup("/games").WithTags("Games");

        // GET /games
        // first parameter is pattern and second is the handler
        group.MapGet("/", async (GameStoreContext dbContext) =>
            await dbContext.Games
                .Include(game => game.Genre)
                .Select(game => new GameSummaryDto(
                    game.Id,
                    game.Title,
                    game.Genre!.Name,
                    game.Price,
                    game.ReleaseDate
                ))
                .AsNoTracking() // AsNoTracking is an optimization that tells Entity Framework Core not to track the retrieved entities in the change tracker, which can improve performance when we only need to read data without modifying it
                .ToListAsync()
        );

        // GET /games/{id}
        group.MapGet("/{id}", async (int id, GameStoreContext dbContext) =>
        {
            var game = await dbContext.Games
                .Include(g => g.Genre)
                .FirstOrDefaultAsync(g => g.Id == id);

            if (game is null)
            {
                return Results.NotFound();
            }

            // Create dto 
            GameDetailsDto gameDto = new (
                game.Id,
                game.Title,
                game.GenreId,
                game.Price,
                game.ReleaseDate
            );

            return Results.Ok(gameDto);
            
        }).WithName(GetGameEndpoint);

        // POST /games
        group.MapPost("/", async (CreateGameDto newGame, GameStoreContext dbContext) =>
        {
            Game game = new ()
            {
                Title = newGame.Title,
                GenreId = newGame.GenreId,
                Price = newGame.Price,
                ReleaseDate = newGame.ReleaseDate
            };

            dbContext.Games.Add(game);
            await dbContext.SaveChangesAsync();

            // After we execute SaveChanges, the game object will have its Id property populated with the value generated by the database.
            // We can then use this Id to create a GameDetailsDto and return it in the response

            GameDetailsDto gameDto = new (
                game.Id,
                game.Title,
                game.GenreId,
                game.Price,
                game.ReleaseDate
            );

            return Results.CreatedAtRoute(GetGameEndpoint, new { id = gameDto.Id }, gameDto);
        });

        // PUT /games/{id}
        group.MapPut("/{id}", async (int id, UpdateGameDto updatedGame, GameStoreContext dbContext) =>
        {
            var existingGame = await dbContext.Games.FindAsync(id);
            if (existingGame is null)
            {
                return Results.NotFound();
            }
            existingGame.Title = updatedGame.Title;
            existingGame.GenreId = updatedGame.GenreId;
            existingGame.Price = updatedGame.Price;
            existingGame.ReleaseDate = updatedGame.ReleaseDate;

            await dbContext.SaveChangesAsync();

            return Results.NoContent();
        });

        // DELETE /games/{id}
        group.MapDelete("/{id}", async (int id, GameStoreContext dbContext) =>
        {
            await dbContext.Games
                .Where(g => g.Id == id)
                .ExecuteDeleteAsync();

            return Results.NoContent();
        });
    }

}